### ISSUE TITLE
Implement More Functions

### ISSUE THREAD

**Issue by JacobNickerson** [JacobNickerson/jbash#2]
Add implementation for common functions such as `cd`, `ls`, `mkdir`, `rmdir`, `remove`, etc. There's a lot.

**Comment by JacobNickerson** [comment]
I've implemented `cd`, `mkdir`, and `pwd`, on the file-system-gaming branch as they were necessary for testing some of the file systems methods. Going forward, commands should be implemented on a separate branch or in main, but for now know that those three are already implemented.

**Comment by cbloodsworth** [comment]
Closing issue as a lot of these have been implemented. The remaining commands will be posted as an issue of their own.
