### ISSUE TITLE
Add unit tests using JUnit

### ISSUE THREAD

**Issue by cbloodsworth** [JacobNickerson/jbash#3]
JUnit is a great framework for testing in Java. I'd like to set up a suite of regression tests so that all functionality remains as we expect going forward.

We will want to ensure that our tests are _isolated_, that is, they only test one thing. That is:
```java

test_cmd_ls() {}  // bad: testing too much

// good -- isolated
test_cmd_ls_basic() {}
test_cmd_ls_flagl() {}
test_cmd_ls_flaga() {}
...
```

The reason for this isolation is that if the contract of the command we are testing changes, we won't have to change as much.

If we had one `test_cmd_ls` test, and we changed the implementation of `ls -a` and the contract changed (that is, tests fail because we changed how the command works), then the entire test would fail and we would have to go into the bowels to figure out what went wrong. In the second approach, _ideally_ only `test_cmd_ls_flaga` would fail, and the rest would stay the same.

Contracts changing after tests have been written is a pain, so I'm fine if you only really write tests right before merging, just as long as they exist. I've had it happen all too often where I write tests for how I _think_ a functionality is going to work, and then I change the implementation/interface and the entire thing breaks. Writing good tests is a skill like any other.

**Comment by JacobNickerson** [comment]
I've been implementing unit tests for the file system, while the file system is currently "working" it likely needs more tests to cover as many edge cases as possible.
