### ISSUE TITLE
Add `static final String err(String msg)` to Command abstract class.

### ISSUE THREAD

**Issue by cbloodsworth** [JacobNickerson/jbash#6]
This would have an implementation something like:

```
static final String err(String msg) {
   return this.name + ": " + msg;
}
```

This would allow us for commands to return standardized error messages based on their own name.

**Comment by JacobNickerson** [comment]
im on it gang

**Comment by cbloodsworth** [comment]
This issue has been resolved for a while -- I'm going to close the issue.
