### ISSUE TITLE
Add Javadoc comments for class methods

### ISSUE THREAD

**Issue by JacobNickerson** [JacobNickerson/jbash#7]
The file system API should have Javadoc comments created for each of its methods.

**Comment by JacobNickerson** [comment]
FSAPI javadocs have been implemented :), but I'm keeping this issue open because I know I'll forget to add docs for whatever I do next.

**Comment by cbloodsworth** [comment]
Looks good for now. We'll make a new issue when we find specific areas of the code lacking in documentation.
